version: '3.7'
services:

  tokenexchangetrusedcontainer-service:
    image: dotnetcore/p7core-grpc-greeter-service
    build: GrpcGreeter

    volumes:
      - ${CERTIFICATE_PATH}:/root/.dotnet/https
    ports:
      - 4700:80
      - 4701:443

    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=${ASPNETCORE_URLS}
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${ASPNETCORE_KESTREL_CERTIFICATE_PASSWORD}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=${ASPNETCORE_KESTREL_CERTIFICATE_PATH}
      - ASPNETCORE_HTTPS_PORT=4701