name: Docker Image CI

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build ./src/ --file src/Dockerfile --tag grpc-dotnetcore-play-base-build

    - name: Build GrpcGreeter
      run: docker build ./src/ --file src/GrpcGreeter/Dockerfile --build-arg build_image=grpc-dotnetcore-play-base-build --tag p7core-grpc-greeter-service:$(date +%s)
